Magento 2.2 Compatibility Patch
ebizmarts/magento2-mandrill pull request #51
Opened 2017-09-29 18:34 UTC by Silarn

There was one breaking change in Magento 2.2 - the Mail Transport interface added a new getMessage function requirement.

This change should be backward compatible.

2017-09-29 18:40 UTC, centerax commented
thanks @Silarn . Once the failing test passes, we will merge it.

2017-09-29 19:05 UTC, centerax requested changes

2017-09-29 19:05 UTC, centerax commented on Model/Transport.php
> +    public function getMessage() {
please put the opening brace on a new line.

2017-10-02 12:21 UTC, closed without merging

2017-10-02 13:35 UTC, Silarn commented
Sorry I didn't get to this this weekend, but it looks like it's been handled.

2017-10-02 14:02 UTC, centerax commented
its sorted, thanks @Silarn for your contribution.